### ISSUE TITLE
Win 11 Next text file and defender

### ISSUE THREAD

**Issue by ydvaditya** [svenmauch/WinSlap#14]
hi one of the tweeks is 
removing right click > new item > txt file

can u please help which one is it and removing defender from win 11 totally

**Comment by svenmauch** [comment]
Hi, thank you for your request. I will first start working on Windows 11 support when I begin using Windows 11 myself, which will not be before it's stable release.

> one of the tweeks is
> removing right click > new item > txt file
> can u please help which one is it

WinSlap currently does not offer this tweak and I have no plans for it.
