### ISSUE TITLE
If winget installation fails, the error message will be shown afte each step

### ISSUE THREAD

**Issue by gigabit942007** [svenmauch/WinSlap#18]
I checked some apps to be installed along with some options and because winget could not be installed i had to click on okay after each step.
![image](https://user-images.githubusercontent.com/8338004/145982122-4c0cb6f3-9c3f-4260-886b-cbd683e84b40.png)
![image](https://user-images.githubusercontent.com/8338004/145982146-8403a468-38dc-4c46-a179-177f7ab70f0d.png)
![image](https://user-images.githubusercontent.com/8338004/145982175-cf5a77aa-c1d5-4374-82bf-74caa941af0a.png)

And so on for each step.

Using Win10 21H2

**Comment by svenmauch** [comment]
I can reproduce this and will try and find a fix. Thank you for reporting!

**Comment by svenmauch** [comment]
Fixed in upcoming release (WinSlap 1.7) https://github.com/svenmauch/WinSlap/commit/9d496c9374ad928d3d9697a9b9c2bc994bf18a0b https://github.com/svenmauch/WinSlap/commit/dc629834edbdc9af16fc84881588464c5807cf39
