### ISSUE TITLE
Dont crash completely if task goes wrong

### ISSUE THREAD

**Issue by Wursteintopf** [svenmauch/WinSlap#2]
If one of the tasks goes wrong while slapping WinSlap crashes completely. Would be great if there was just an errormessage "This task went wrong for whatever reason" and the slapping then continues, so I dont have to repick all the stuff I want and start over from scratch.

**Comment by svenmauch** [comment]
After running on Windows 10 (2004) to provoke an error, WinSlap doesn't crash.

![grafik](https://user-images.githubusercontent.com/24568451/86165948-52233300-bb14-11ea-97ec-4dd3d007bc96.png)

Can you clarify which version you are using and how to reproduce the issue?

**Comment by svenmauch** [comment]
Issue could not be reproduced
