### ISSUE TITLE
anyway to revert back a feature i disabled by mistake

### ISSUE THREAD

**Issue by ifelixculpa** [svenmauch/WinSlap#21]
i disabled a feature by mistake any way to get that specific feature back ?

please help

**Comment by svenmauch** [comment]
I'm afraid I can't help with reverting tweaks, please see https://github.com/svenmauch/WinSlap/issues/6

**Comment by ifelixculpa** [comment]
> I'm afraid I can't help with reverting tweaks, please see #6

i think i got the tweak how do i apply that sir ?
