### ISSUE TITLE
 I can't change my energy plan 

### ISSUE THREAD

**Issue by luigizaint** [svenmauch/WinSlap#26]
I can't change my energy plan and I feel like the plan I use doesn't feel like it works at all.
could you help me with that?

**Comment by luigizaint** [comment]
![Captura de pantalla 2024-02-05 114832](https://github.com/svenmauch/WinSlap/assets/159087711/af6e265e-cf80-4bb2-b473-63156ed4d2a4)

**Comment by svenmauch** [comment]
You would need to revert the policy manually.

https://github.com/svenmauch/WinSlap/blob/723b171377c1340cc19c9788d356d5bef7bae06b/WinSlap/Slapper.cs#L350
