### ISSUE TITLE
An error occured while trying to instal winget

### ISSUE THREAD

**Issue by Mikelipcsei** [svenmauch/WinSlap#7]
not sure what happened... updated hp stream to win10 20H2 then a couple of more updates came along and auto installed 3/4 way through winslap install then after stream was finished ran winslap agin with the error above. said to report so here it is.
Mike

**Comment by andrewpayne68** [comment]
same here.

**Comment by AllanRobertson** [comment]
![image](https://user-images.githubusercontent.com/17201935/110372240-0ec28200-801c-11eb-9248-a9589233ab90.png)

Me too in a Windows 10 20H2 VM hosted in VirtualBox 6.1

**Comment by sdhnewman** [comment]
So, winslap is completely broken when used on a clean 21H1 install. It's trying to install a pre-release version of winget and failing. I planned to use it to create a new Windows image, and I didn't expect it to be broken.

Installing winget manually didn't help. It might be a good idea to test to see if winget is already installed before installing it.

**Comment by svenmauch** [comment]
Thank you for reporting this bug. It should be fixed in v1.5. Please report back if you still encounter any problems.

**Comment by sdhnewman** [comment]
Thank you Sven

**Comment by tommiefr** [comment]
I still get this error on the 1.5 version. It is a fresh installed W10
How to solve this?
